server:
  name: api-1
  port: 9999

spring:
  redis:
    host: localhost
    port: 6379
  cloud:
    gateway:
      filter:
        request-rate-limiter:
          deny-empty-key: true
      routes:
        - id: rate_limiter_route
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/**
          filters:
            - name: RequestRateLimiter
              args:
                rate-limitter: "#{@customRedisRateLimiter}"
                key-resolver: "#{@apiKeyResolver}"


logging:
  level:
    root: DEBUG