#Setting the logging levels for the service
logging:
  level:
    root: info
    com:
      ms:
        authentication: debug

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  servlet:
    contextPath:   /auth
