spring:
  application:
    name: license
  config:
    import: "optional:configserver:http://localhost:8761/eureka/config"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/