spring:
  profiles:
    include:
      - mysql
  batch:
    job:
      names: ${job.name:NONE}

logging:
  level:
    org:
      springframework:
        batch: DEBUG

---
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: mysql
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver



