
server:
  port: 8092

  prifiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/system_design_interview?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
---
message:
  sms:
    api-key:
    secret:
